name:                tiger
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/tiger#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text

library:
  source-dirs: src

executables:
  tiger:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - tiger
